security:
    hide_user_not_found: false

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Cerad\Bundle\UserBundle\Entity\User: 
            id: cerad_user__user_encoder
        
    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_SCORE_ENTRY: [ROLE_USER, ROLE_SCORE_ENTRY]
        ROLE_SCORE_ADMIN: [ROLE_USER, ROLE_SCORE_ENTRY, ROLE_SCORE_ADMIN]
        ROLE_ASSIGNOR:    [ROLE_USER, ROLE_ASSIGNOR]
        
        ROLE_ADMIN:       [ROLE_USER, ROLE_ASSIGNOR, ROLE_SCORE_ADMIN, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ASSIGNOR, ROLE_SCORE_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory__user_provider:
            memory:
                users:
                    user:     { password: user894,  roles: [ 'ROLE_USER' ]  }
                    admin:    { password: admin894, roles: [ 'ROLE_ADMIN' ] }
                    su:       { password: su894,    roles: [ 'ROLE_SUPER_ADMIN'] }
                    assignor: { password: assign,   roles: [ 'ROLE_ASSIGNOR'] }
                    
        cerad_user__user_provider:
            id: cerad_user__user_provider
            
        chained__user_provider:
            chain:
                providers: [ in_memory__user_provider, cerad_user__user_provider ]
                
# ================================================================================
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/         
            anonymous: ~
            
            form_login:
                provider:            chained__user_provider
                login_path:          cerad_user__user__login
                check_path:          cerad_user__user__login_check
                default_target_path: cerad_tourn__home

                username_parameter:  cerad_user__user__login[username]
                password_parameter:  cerad_user__user__login[password]
                csrf_parameter:      cerad_user__user__login[_token]
                csrf_provider:       form.csrf_provider
                intention:           authenticate
                
            logout:
                path:   cerad_user__user__logout
                target: cerad_tourn__welcome
                                
            remember_me:
                key:      "%secret%"
                lifetime: 31536000  # 365 days in seconds
                path:     cerad_tourn__welcome
                domain:   ~
                name:     zayso_remember_me
                remember_me_parameter: cerad_user__user__login[rememberMe]

    access_control:
        - { path: '^/[A-Za-z0-9_-]+/admin',roles: ROLE_ASSIGNOR }


